version: '3.6'

volumes:
  app-db-data2:

services:
  db:
    image: postgres:9.5.14
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: explorer
      POSTGRES_USER: noah
      POSTGRES_PASSWORD: password
    volumes:
      - app-db-data2:/var/lib/postgresql/data

  centrifugo:
    image: centrifugo/centrifugo
    volumes:
      - ./tmp/centrifugo:/centrifugo
      - ./tmp/var/logs/centrifugo:/var/log/centrifugo
    ports:
      - 8800:8000
